<#import "shared-components.ftlh" as com>
<h1>Welcome to the demo application for Spring Boot with HTMX</h1>
<p>This application uses Apache Freemarker and HTMX on to of a Spring Boot app to create a simple yet functional base
    for a new web project.</p>
<p>If you navigate the site normally, you can observe in the network tab, that the server will send only the new HTML
    necessary for the navigation you just triggered. But all clicks should also work if you open them in a new tab, or
    with javascript disabled.</p>
<p>The relevant blogpost can be read on my <a href="https://www.codecentric.de/wissens-hub/blog/spring-boot-and-htmx-the-boring-app">employers blog</a> or on my <a href="https://github.com/mircohacker/Spring-Boot-and-HTMX">GitHub</a>
</p>